### ISSUE TITLE
Any known proto?

### ISSUE THREAD

**Issue by nkawanto** [Royster0/RoySauce-60#2]
Hey there!

I'm currently seeing what existing open-sourced model that I could use as a reference/base, and found your project! I'm wondering if there's any known prototype being made so far, maybe by yourself? 

I'm trying to figure out if I'd want to proto this as a 3d print (just as a sanity check to see if everything fits), or if it's ready to be CNC'd (I'm making a one-off for personal use haha). Please let me know, thank you!

**Comment by Royster0** [comment]
Hey! I know of only one person who got it manufactured and they said everything worked fine. I would edit the bottom case to add a hole underneath the JST connector on your PCB of choice though.
